import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import Navbar from "@/components/Navbar";
import { redirect } from "next/navigation";
import { CreateUserIfNotFound } from "@/lib/dbService";
import { User } from "@prisma/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  if (session?.user?.email == null) {
    redirect("/api/auth/signin");
  }

  const user = await CreateUserIfNotFound(session.user);

  return (
    <html lang="en">
      <body className={`${inter.className} p-8  space-y-8 `}>
        <Navbar user={user} />
        {children}
      </body>
    </html>
  );
}
